// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjlCZhQVwHNUc6cFrsHdjxwtFo0oGprUs',
    appId: '1:199850076061:android:8fd1285be5c6f78434f174',
    messagingSenderId: '199850076061',
    projectId: 'saudiandatesclassifier',
    storageBucket: 'saudiandatesclassifier.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnd3KU00jXZyXwr7iXIG0XqvKaUkA6u3k',
    appId: '1:199850076061:web:cb7d4af489bc583f34f174',
    messagingSenderId: '199850076061',
    projectId: 'saudiandatesclassifier',
    authDomain: 'saudiandatesclassifier.firebaseapp.com',
    storageBucket: 'saudiandatesclassifier.firebasestorage.app',
    measurementId: 'G-8K2HB8N5PG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoEILwUZZ66WWdmvQ-MMPQVpycNQCm1po',
    appId: '1:199850076061:ios:df88d705aad3f12334f174',
    messagingSenderId: '199850076061',
    projectId: 'saudiandatesclassifier',
    storageBucket: 'saudiandatesclassifier.firebasestorage.app',
    iosBundleId: 'com.example.suadiniansDates',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoEILwUZZ66WWdmvQ-MMPQVpycNQCm1po',
    appId: '1:199850076061:ios:df88d705aad3f12334f174',
    messagingSenderId: '199850076061',
    projectId: 'saudiandatesclassifier',
    storageBucket: 'saudiandatesclassifier.firebasestorage.app',
    iosBundleId: 'com.example.suadiniansDates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnd3KU00jXZyXwr7iXIG0XqvKaUkA6u3k',
    appId: '1:199850076061:web:f0a648dcbdfdd4f534f174',
    messagingSenderId: '199850076061',
    projectId: 'saudiandatesclassifier',
    authDomain: 'saudiandatesclassifier.firebaseapp.com',
    storageBucket: 'saudiandatesclassifier.firebasestorage.app',
    measurementId: 'G-2GXRL8NPWJ',
  );

}